### ISSUE TITLE
🚀 - Database Schema Model for Orders

### ISSUE THREAD

**Issue by davidsaulrodriguez** [davidsaulrodriguez/shop-portal#10]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

This feature request is not related to any current issue but is needed to get the project in a working state.

We need a way to keep track of orders and even reference them to the cart and to the user equally. This way we can give the user a way to see their order history and even the details of those orders.

At a minimum this schema should contain the following objects:

- [x] Cart (type of `Schema.Types.ObjectId` ; reference `Cart` Schema)
- [x] Order (type of `Schema.Types.ObjectId` ; reference `Order` Schema)
- [x] Total (type of `Number` ; default to `0`)
- [x] Created At (type of Date; default to Date.now)
- [x] Updated At (type of Date)

**Describe the solution you'd like**

This schema model should be created using Mongoose for MongoDB.

**Comment by davidsaulrodriguez** [comment]
This issue was closed with commit https://github.com/davidsaulrodriguez/shop-portal/commit/70bc9b2b9843801314b4a368457e0b99b4dcbd94
