### ISSUE TITLE
🚀 - Database Schema Model for Users

### ISSUE THREAD

**Issue by davidsaulrodriguez** [davidsaulrodriguez/shop-portal#4]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

This feature request is not related to any current issue but is needed to get the project in a working state.

A user schema model needs to be created for the database. This schema model will correlate with using PassportJS as a login system and use `passport-local` , `passport-google-oauth2`, and `passport-facebook`.

At a minimum it needs to contain:

- [x] Username (optional)
- [x] Email
- [x] Password
- [x] First name
- [x] Last name
- [x] Merchant (Referencing the Merchant Schema)
- [x] Role (an Enum with the values of: Admin, Merchant and User [or Member])
- [x] Provider (defaulted to Email)
- [x] Phone Number
- [x] GoogleID (for login via Google)
- [x] FacebookID (for login via Facebook)
- [x] Reset Password Token (type of String)
- [x] Reset Password Expiry (type of Date)
- [x] Created At (type of Date)
- [x] Updated At (type of Date)

**Describe the solution you'd like**

This schema model should be created using Mongoose for MongoDB.

**Comment by davidsaulrodriguez** [comment]
This issue was closed with commit https://github.com/davidsaulrodriguez/shop-portal/commit/70bc9b2b9843801314b4a368457e0b99b4dcbd94
