### ISSUE TITLE
🚀 - Landing Page 

### ISSUE THREAD

**Issue by jdavidrice** [davidsaulrodriguez/shop-portal#45]
The first page viewed by all site users. Will link to login/signup and to main store page. Should feature a few select items from the store. 

- [x] Hero Style Carousel
  - [ ] Featured Products
  - [ ] Featured Categories
- [ ] 3 to 4 Featured Categories on page
  - [ ] Paginate items (optional / nice to have)
- [ ] 3 to 6 Featured Products on page
  - [ ] Paginate items (optional / nice to have)
