### ISSUE TITLE
🚀 - Database Schema Model for Address

### ISSUE THREAD

**Issue by davidsaulrodriguez** [davidsaulrodriguez/shop-portal#6]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

This feature request is not related to any current issue but is needed to get the project in a working state.

There needs to be an Address Schema to store a user's address in the database. This schema should also reference the User Schema.

At a minimum it need to contain these properties:

- [x] User (type of `Schema.Types.ObjectId` ; referencing the User schema)
- [x] Address [Line 1] (type of `String`)
- [x] Address [Line 2] (type of `String`)
- [x] City (type of `String`)
- [x] State (type of `String`)
- [x] Country (type of `String`)
- [x] Zip (type of `String`)
- [x] isDefault (type of `Boolean` ; default to `false`)
- [x] Created At (type of Date; default to `Date.now`)
- [x] Updated At (type of Date)

**Describe the solution you'd like**

This schema model should be created using Mongoose for MongoDB.

**Comment by davidsaulrodriguez** [comment]
This issue was closed with commit https://github.com/davidsaulrodriguez/shop-portal/commit/70bc9b2b9843801314b4a368457e0b99b4dcbd94
