### ISSUE TITLE
🚀 - Database Schema Model for Categories

### ISSUE THREAD

**Issue by davidsaulrodriguez** [davidsaulrodriguez/shop-portal#7]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

This feature request is not related to any current issue but is needed to get the project in a working state.

Every product has a category that it falls under. You can also browse products by their category and this eCommerce store is no different. So a Category schema is needed and a way to add slugs to each category. - A slug can be created easily by using the `mongoose-slug-generator` npm package.

At a minimum this schema should contain the following objects:

- [x] ID (type of `Schema.ObjectId` ; **auto** set to `true`)
- [x] Name (type of `String` ; **trim** set to `true`)
- [x] Slug (type of `String` ; slug: 'name' ; **unique** set to `true`)
- [x] Image (data: Buffer ; contentType: String)
- [x] Description (type of `String` ; **trim** set to `true`)
- [x] isActive (type of `Boolean` ; default to `true`)
- [x] Products (type of `Schema.Types.ObjectId` ; referencing `Product` Schema)
- [x] Created At (type of Date; default to Date.now)
- [x] Updated At (type of Date)

**Describe the solution you'd like**

This schema model should be created using Mongoose for MongoDB.

**Comment by davidsaulrodriguez** [comment]
This issue was closed with commit https://github.com/davidsaulrodriguez/shop-portal/commit/70bc9b2b9843801314b4a368457e0b99b4dcbd94
