### ISSUE TITLE
🚀 - Database Schema Model for Products

### ISSUE THREAD

**Issue by davidsaulrodriguez** [davidsaulrodriguez/shop-portal#8]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

This feature request is not related to any current issue but is needed to get the project in a working state.

You can't have a store without products. This is where the Product Schema comes into play. Like the category schema, each product should also have a slug and we will do this using the `mongoose-slug-generator` npm package.

This schema will also have to reference the Brand Schema so that each product can (optionally) reference the Brand it belongs to.

At a minimum this schema should contain the following objects:

- [x] SKU (type of `String` ; **unique** set to `true`)
- [x] Name (type of `String` ; **trim** set to `true`)
- [x] Slug (type of `String` ; slug: 'name' ; **unique** set to `true`)
- [x] imageURL (type of `String`)
- [x] imageKey (type of `String`)
- [x] Description (type of `String` ; **trim** set to`true`)
- [x] Quantity (type of `Number`)
- [x] Price (type of `Number`)
- [x] Taxable (type of `Boolean` ; default to `false`)
- [x] isActive (type of `Boolean` ; default to `true`)
- [x] Brand (type of `Schema.Types.ObjectId` ; reference `Brand` Schema ; default to `null`)
- [x] Created At (type of Date; default to Date.now)
- [x] Updated At (type of Date)

**Describe the solution you'd like**

This schema model should be created using Mongoose for MongoDB.

**Comment by davidsaulrodriguez** [comment]
This issue was closed with commit https://github.com/davidsaulrodriguez/shop-portal/commit/70bc9b2b9843801314b4a368457e0b99b4dcbd94
