### ISSUE TITLE
🚀 - Database Schema Model for Brand

### ISSUE THREAD

**Issue by davidsaulrodriguez** [davidsaulrodriguez/shop-portal#9]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

This feature request is not related to any current issue but is needed to get the project in a working state.

Most, if not all products have a Brand. This is where the Brand schema comes into play. Like the Product and Category schemas this schema will also generate a slug. This will be done using the `mongoose-slug-generator` and (optionally) reference the Merchant schema.

At a minimum this schema should contain the following objects:

- [x] Name (type of `String`)
- [x] Slug (type of `String` ; slug: 'name' ; **unique** set to `true`)
- [x] Image (data: `Buffer` ; contentType: `String`)
- [x] Description (type of `String` ; **trim** set to `true`)
- [x] isActive (type of `Boolean` ; default to `true`)
- [x] Merchant (type of `Schema.Types.ObjectId` ; reference `Merchant` Schema ; default to `null`)
- [x] Created At (type of Date; default to Date.now)
- [x] Updated At (type of Date)

**Describe the solution you'd like**

This schema model should be created using Mongoose for MongoDB.

**Comment by davidsaulrodriguez** [comment]
This issue was closed with commit https://github.com/davidsaulrodriguez/shop-portal/commit/70bc9b2b9843801314b4a368457e0b99b4dcbd94
